apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-demo
  labels:
    app: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-demo
  template:
    metadata:
      labels:
        app: cloud-demo
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
